spring:
  main:
    banner-mode: off
camel:
  springboot:
    main-run-controller: false # true for long-running camel tasks
dhis2:
  inventory:
    hosts:
      playdev:
        type: dhis2
        baseUrl: https://play.dhis2.org/de
        username: admin
        password: district
      playdemo:
        type: dhis2
        baseUrl: https://play.dhis2.org/demo
        username: admin
        password: district
    groups:
      play:
        - playdev
        - playdemo
    verify: true
